# Generated by Django 4.2.16 on 2024-12-15 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_name', models.CharField(max_length=100)),
                ('producer_channel', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='videos.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Streaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streaming_name', models.CharField(max_length=100)),
                ('streaming_path', models.CharField(max_length=255)),
                ('streaming_created_at', models.DateField(auto_now_add=True)),
                ('streaming_channel', models.CharField(max_length=30)),
                ('streaming_description', models.TextField()),
                ('streaming_is_live', models.BooleanField(default=False)),
                ('streaming_producer', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StreamingArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streaming_article_title', models.CharField(max_length=100)),
                ('streaming_article_deleted', models.BooleanField(default=False)),
                ('streaming_article_updated_at', models.DateField(auto_now=True)),
                ('streaming_article_created_at', models.DateField(auto_now_add=True)),
                ('streaming_article_content', models.CharField(max_length=255)),
                ('streaming_article_channel', models.CharField(max_length=30)),
                ('view_count', models.IntegerField()),
                ('streaming_article_producer', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='videos.producer')),
                ('streaming_pk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='videos.streaming')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=100)),
                ('video_path', models.CharField(max_length=255)),
                ('video_created_at', models.DateField(auto_now_add=True)),
                ('video_script', models.BooleanField(default=False)),
                ('video_channel', models.CharField(max_length=30)),
                ('video_thumbnail_path', models.CharField(max_length=255)),
                ('video_status', models.CharField(max_length=30)),
                ('video_producer', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='videos.producer')),
            ],
        ),
        migrations.CreateModel(
            name='VideoArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_article_title', models.CharField(max_length=100)),
                ('video_article_deleted', models.BooleanField(default=False)),
                ('video_article_updated_at', models.DateField(auto_now=True)),
                ('video_article_created_at', models.DateField(auto_now_add=True)),
                ('video_article_content', models.CharField(max_length=255)),
                ('video_channel', models.CharField(max_length=30)),
                ('view_count', models.IntegerField()),
                ('video_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
                ('video_producer', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='videos.producer')),
            ],
        ),
        migrations.CreateModel(
            name='StreamingArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streaming_comment_content', models.TextField()),
                ('streaming_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.streamingarticle')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('article_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.videoarticle')),
            ],
        ),
    ]
