# Generated by Django 4.2.16 on 2024-12-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoarticle',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
