# Generated by Django 4.2.16 on 2024-12-17 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_videoarticle_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoarticle',
            name='video_channel',
        ),
    ]
